server:
  port: 8083
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/MICROSERVICES
    username: postgres
  
  application:
    name: eurekaclient
eureka:
   client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true


logging:
  level:
    com:
      example:
        createuser:
          repostery: trace




